version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8888:8000"
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"
  

  db:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    restart: on-failure


  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/user/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
