# Generated by Django 5.1 on 2024-08-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carmodel_auto_parks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='auto_parks',
            new_name='auto_park',
        ),
    ]
