# Generated by Django 5.1 on 2024-08-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_auto_parks_carmodel_auto_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
