# Generated by Django 5.0.8 on 2024-08-20 11:28

import django.core.validators
from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_carmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Z](?=.*[A-Z])?(?=.*[a-z])?(\\S){3,20}$', ['Brand name must start with capital letter', 'Brand name must contain min 3 max 20 characters without spaces'])]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.FileService.upload_car_photo, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
    ]
