# Generated by Django 5.0.8 on 2024-08-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_carmodel_body_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='auto_park',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='photo',
        ),
    ]
